#!/bin/env bash
#$ -N demo-gpu  ## job name
#$ -cwd         ## use current working directory
#$ -j yes       ## merge stdout and stderr
#$ -q gpu.q     ## submit to GPU queue

t0=$(date --rfc-3339=seconds)

echo "QUEUE: $QUEUE"
echo "HOSTNAME: $HOSTNAME"
echo "SGE_GPU: $SGE_GPU"
export CUDA_VISIBLE_DEVICES=$SGE_GPU

echo "Singularity executable: $(which singularity)"

t1=$(date --rfc-3339=seconds)
echo "Duration: $t0 -- $t1"
